name: password_compromised
homepage: https://github.com/betarabbit/password-compromised
description: A dart package to determine if a password is compromised by checking with the Have I Been Pwned API.
version: 1.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  crypto: ^3.0.1

dev_dependencies:
  flutter_lints: ^1.0.4
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  test: ^1.21.0
  random_string: ^2.3.1
