name: password_compromised
homepage: https://github.com/betarabbit/password-compromised
description: A dart package to determine if a password is compromised by checking with the Have I Been Pwned API.
version: 1.0.0
author: Tianxiao Ma <matx2215@outlook.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  crypto: ^2.0.6

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  random_string: ^1.1.0
